version: '3.8'

services:
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  backend:
    build: .
    ports:
      - "3017:3017"
    depends_on:
      - mongo
    env_file:
      - .env
    volumes:
      - .:/usr/src/app
    command: npm run start:dev

volumes:
  mongo-data:
